### ISSUE TITLE
Add proper exception handling when starting and killing Tendermint process.

### ISSUE THREAD

**Issue by angrybayblade** [valory-xyz/open-autonomy#1037] opened 2022-06-29 11:31 UTC
```output
    self = <deployments.Dockerfiles.localnode.tendermint.TendermintNode object at 0x12cd607f0>
    def _stop_tm_process(self) -> None:
        """Stop a Tendermint node process."""
        if self._process is None:
            return
        if platform.system() == "Windows":  # pragma: nocover
            os.kill(self._process.pid, signal.CTRL_C_EVENT)  # type: ignore  # pylint: disable=no-member
        else:
>           os.killpg(os.getpgid(self._process.pid), signal.SIGTERM)
E           ProcessLookupError: [Errno 3] No such process
deployments/Dockerfiles/localnode/tendermint.py:195: ProcessLookupError
```

From this CI run: https://github.com/valory-xyz/open-autonomy/runs/7110583220?check_suite_focus=true

**Comment by Adamantios** [comment] 2022-06-29 11:37
Possible duplicate of #989 .

**Closed** 2022-08-08 15:12 UTC
Labels: test, priority
