### ISSUE TITLE
magic numbers

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1193] opened 2022-08-15 19:23 UTC
these should become constants with a meaningful name. There might be more I didn't systematically assess.

also noticed this comment, whereas it seems to me gas estimation works fine. I used a multiplier for the current gasPrice in order to increase changes of being included in the next block.  
https://github.com/valory-xyz/open-autonomy/blob/fb43976a48028b0e8c7f7690ca51ffb3174876ea/packages/valory/contracts/gnosis_safe_proxy_factory/contract.py#L146

### magic numbers
https://github.com/valory-xyz/open-autonomy/blob/285b699bca07bd9ac21bf26ab7d43ac5d76f6abb/packages/valory/contracts/gnosis_safe/contract.py#L212
https://github.com/valory-xyz/open-autonomy/blob/285b699bca07bd9ac21bf26ab7d43ac5d76f6abb/packages/valory/contracts/gnosis_safe/contract.py#L430
https://github.com/valory-xyz/open-autonomy/blob/285b699bca07bd9ac21bf26ab7d43ac5d76f6abb/packages/valory/contracts/gnosis_safe/contract.py#L456
https://github.com/valory-xyz/open-autonomy/blob/285b699bca07bd9ac21bf26ab7d43ac5d76f6abb/packages/valory/contracts/gnosis_safe_proxy_factory/contract.py#L147
https://github.com/valory-xyz/open-autonomy/blob/495561dd996aeb1149b06083ff135c4c3c6bd4ea/packages/valory/contracts/multisend/contract.py#L150

https://github.com/valory-xyz/open-autonomy/blob/495561dd996aeb1149b06083ff135c4c3c6bd4ea/packages/valory/contracts/gnosis_safe/contract.py#L212
https://github.com/valory-xyz/open-autonomy/blob/495561dd996aeb1149b06083ff135c4c3c6bd4ea/packages/valory/contracts/gnosis_safe/contract.py#L430
https://github.com/valory-xyz/open-autonomy/blob/495561dd996aeb1149b06083ff135c4c3c6bd4ea/packages/valory/contracts/gnosis_safe/contract.py#L456
https://github.com/valory-xyz/open-autonomy/blob/495561dd996aeb1149b06083ff135c4c3c6bd4ea/packages/valory/contracts/gnosis_safe_proxy_factory/contract.py#L147

**Comment by DavidMinarsch** [comment] 2022-08-16 06:22
Closing as it is basically a duplicate of #1021

**Closed by DavidMinarsch** 2022-08-16 06:22 UTC
