### ISSUE TITLE
issue: Custom components are not published with --push-missing

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#2255] opened 2024-09-01 20:02 UTC
### When publishing from an existing agent, custom components are not pushed to the packages directory.
Describe your issue here.

**Comment by Adamantios** [comment] 2024-09-18 10:51
Duplicate of https://github.com/valory-xyz/open-autonomy/issues/2226.

**Closed by Adamantios** 2024-09-18 10:51 UTC
